[project]
name = "tovald"
version = "0.0.0"
description = "Publish rich markdown documentation to Confluence"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "myst-parser==4.0",
    "sphinx==8.1",
    "sphinx-toolbox==3.8",
    "sphinxcontrib-confluencebuilder==2.8",
]

[tool.uv]
dev-dependencies = [
    "black",
    "pre-commit",
    "pytest>=8.3.3",
    "ruff",
    "yamllint",
]
